### ISSUE TITLE
MVP 

### ISSUE THREAD

**Issue by RonaldDijkstra** [DefactoSoftware/Questionnaire#4]
- [ ] Use URL params for result graphics but scope to the answers only
- [ ] Add real content (Questions and all) 
- [ ] Require all answers before submits

**Comment by sn3p** [comment]
These todos are related to the implementation ([found here](https://github.com/DefactoSoftware/website/pull/1447)).

**Comment by sn3p** [comment]
These todos are related to the implementation ([found here](https://github.com/DefactoSoftware/website/pull/1447)).
